// ============================================================
// NEUE QUIZFRAGEN – generiert zur Erweiterung der Fragen-Datenbank
// Erstellt aus Azubi-Physio-Perspektive auf Basis der bestehenden Lernthemen (data.js)
// Einfach VOR die schließende eckige Klammer "];" von quizBank in data.js einfügen.
// ============================================================
// --- t_ws_grund (neu) ---
{id:"q237",topic:"t_ws_grund",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"leicht",type:"fakt",q:"Wie viele Kreuzwirbel sind zum Os sacrum (Kreuzbein) verschmolzen?",opts:["4","5","6","7"],a:1,exp:"5 Kreuzwirbel verschmelzen zum Os sacrum.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q238",topic:"t_ws_grund",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"verstaendnis",q:"Welche Aufgabe hat die physiologische doppel-S-förmige Krümmung der Wirbelsäule vor allem?",opts:["Federung/Stoßdämpfung bei axialer Belastung (z. B. Gehen, Springen)","Vollständige Bewegungslosigkeit der WS","Vergrößerung des Rückenmarkskanals","Fixierung der Rippen am Sternum"],a:0,exp:"Die Doppel-S-Form wirkt wie eine Feder und dämpft axiale Stöße beim Gehen, Laufen und Springen ab.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_kopfgelenke (neu) ---
{id:"q239",topic:"t_kopfgelenke",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"verstaendnis",q:"Wie unterscheiden sich oberes und unteres Kopfgelenk in ihrem Gelenktyp und ihrer Hauptbewegung?",opts:["Oberes Kopfgelenk = Nickbewegungen (Ellipsoidgelenk), unteres = Rotation (Radgelenk)","Beide sind reine Radgelenke mit identischer Funktion","Oberes Kopfgelenk = Rotation, unteres = Nickbewegungen","Beide ermöglichen ausschließlich Lateralflexion"],a:0,exp:"Das obere Kopfgelenk (Art. atlantooccipitalis) ist ellipsoidgelenkartig für Nickbewegungen, das untere (Art. atlantoaxialis) radgelenkartig für Rotation.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q240",topic:"t_kopfgelenke",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"schwer",type:"klinik",q:"Welche Konsequenz kann eine Instabilität des Lig. transversum atlantis (z. B. bei rheumatoider Arthritis) haben?",opts:["Erhöhtes Risiko einer Kompression des zervikalen Rückenmarks durch den Dens axis","Verbesserte Rotationsfähigkeit der HWS","Keine klinische Relevanz","Ausschließlich Sensibilitätsverlust im Gesicht"],a:0,exp:"Fällt die Sicherungsfunktion des Lig. transversum atlantis aus, kann der Dens axis bei Flexion das zervikale Rückenmark komprimieren – ein Sicherheitsaspekt bei der HWS-Behandlung.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_ws_bandscheibe (neu) ---
{id:"q241",topic:"t_ws_bandscheibe",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"verstaendnis",q:"Warum ist eine Bandscheibe morgens nach dem Aufstehen typischerweise wasserreicher/höher als abends?",opts:["Weil sie nachts im Liegen entlastet wird und Flüssigkeit aufnimmt","Weil sie nachts stärker belastet wird","Es gibt keinen Tagesunterschied","Weil sich nachts neues Kollagen bildet"],a:0,exp:"Nachts im Liegen sinkt der Druck auf die Bandscheibe, wodurch sie Flüssigkeit aufnimmt; tagsüber unter Belastung gibt sie wieder Flüssigkeit ab.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q242",topic:"t_ws_bandscheibe",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"anatomie",q:"Wie verändert sich der Kollagentyp innerhalb des Anulus fibrosus von außen nach innen?",opts:["Außen Kollagen Typ I (zugfest), innen Kollagen Typ II (faserknorpelig)","Außen Typ II, innen Typ I","Durchgehend nur Kollagen Typ I","Durchgehend nur Kollagen Typ II"],a:0,exp:"Die Außenzone des Anulus fibrosus besteht aus zugfestem Kollagen Typ I, die Innenzone aus faserknorpeligem Kollagen Typ II.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q243",topic:"t_ws_bandscheibe",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"physio",q:"Warum gilt Bewegungsmangel als ungünstig für die Bandscheibengesundheit?",opts:["Weil ohne Belastungswechsel die Diffusionsernährung der Bandscheibe eingeschränkt ist","Weil Bewegungsmangel den Wassergehalt der Bandscheibe erhöht","Weil Bandscheiben Muskelkraft zur Ernährung benötigen","Es besteht kein Zusammenhang"],a:0,exp:"Da die Bandscheibe nur über Diffusion (Be-/Entlastungswechsel) ernährt wird, verschlechtert dauerhafter Bewegungsmangel ihre Nährstoffversorgung.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_ruecken_muskulatur (neu) ---
{id:"q244",topic:"t_ruecken_muskulatur",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"anatomie",q:"Welchem Teilsystem des lateralen Stranges wird der M. longissimus zugeordnet?",opts:["Sakrospinales System","Transversospinales System","Intertransversales System","Spinotransversales System"],a:0,exp:"M. longissimus und M. iliocostalis gehören zum sakrospinalen System des lateralen Stranges.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q245",topic:"t_ruecken_muskulatur",cat:"anatomie",sub:"Wirbelsäule & Rumpf",diff:"leicht",type:"anatomie",q:"Welche Muskeln überdecken die autochthone Rückenmuskulatur oberflächlich?",opts:["M. latissimus dorsi, M. trapezius, Mm. rhomboidei, M. levator scapulae","M. quadriceps femoris und M. iliopsoas","M. rectus abdominis und M. obliquus externus","M. gluteus maximus und medius"],a:0,exp:"Oberflächlich wird die autochthone Rückenmuskulatur von M. latissimus dorsi, M. trapezius, Mm. rhomboidei und M. levator scapulae überdeckt.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_thorax_atmung (neu) ---
{id:"q246",topic:"t_thorax_atmung",cat:"anatomie",sub:"Thorax & Atmung",diff:"leicht",type:"fakt",q:"Welche Muskeln zählen zur Atemhilfsmuskulatur?",opts:["M. pectoralis major/minor, Mm. scaleni, M. sternocleidomastoideus","M. transversus abdominis allein","M. quadriceps femoris","M. gluteus maximus"],a:0,exp:"Atemhilfsmuskeln sind u. a. M. pectoralis major/minor, Mm. scaleni und M. sternocleidomastoideus – sie unterstützen bei erhöhtem Atembedarf.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q247",topic:"t_thorax_atmung",cat:"anatomie",sub:"Thorax & Atmung",diff:"mittel",type:"fakt",q:"Welches Rückenmarksegment gilt als Kennmuskel-Segment für das Zwerchfell?",opts:["C4","L1","Th6","S1"],a:0,exp:"Das Zwerchfell wird vom N. phrenicus innerviert, Kennmuskel-Segment ist C4 – relevant z. B. bei hohen Querschnittlähmungen.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_bauchwand (neu) ---
{id:"q248",topic:"t_bauchwand",cat:"anatomie",sub:"Bauch & Becken",diff:"mittel",type:"verstaendnis",q:"Welche Bewegung entsteht bei beidseitiger Kontraktion der geraden und schrägen Bauchmuskeln?",opts:["Ventralflexion des Rumpfes, Beckenaufrichtung, Bauchpresse und Ausatmung","Ausschließlich Rotation nach beiden Seiten","Ausschließlich Lateralflexion","Streckung der Wirbelsäule"],a:0,exp:"Beidseitige Kontraktion bewirkt Ventralflexion, Aufrichtung des Beckens, Bauchpresse und Unterstützung der Ausatmung.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q249",topic:"t_bauchwand",cat:"anatomie",sub:"Bauch & Becken",diff:"mittel",type:"anatomie",q:"Wo setzt der M. rectus abdominis an?",opts:["Am Schambein (Os pubis)","Am Trochanter major","An der Tuberositas tibiae","An der Crista iliaca"],a:0,exp:"Der M. rectus abdominis entspringt an Rippenknorpel 5–7/Proc. xiphoideus und setzt am Schambein an.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q250",topic:"t_bauchwand",cat:"anatomie",sub:"Bauch & Becken",diff:"schwer",type:"anatomie",q:"Was geschieht oberhalb der Linea arcuata mit dem M. obliquus internus abdominis?",opts:["Er spaltet sich in ein vorderes und ein hinteres Blatt der Rectusscheide","Er verläuft ausschließlich vor dem M. rectus abdominis","Er verschwindet vollständig","Er verläuft ausschließlich hinter dem M. rectus abdominis"],a:0,exp:"Oberhalb der Linea arcuata spaltet sich der M. obliquus internus in ein vorderes und hinteres Blatt der Rectusscheide; unterhalb ziehen alle lateralen Muskeln nur ins vordere Blatt.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_beckenboden (neu) ---
{id:"q251",topic:"t_beckenboden",cat:"anatomie",sub:"Bauch & Becken",diff:"leicht",type:"anatomie",q:"Welche zusätzliche Struktur durchzieht den Beckenboden bei der Frau neben Rectum und Urethra?",opts:["Vagina","Ösophagus","Trachea","Aorta"],a:0,exp:"Bei der Frau durchziehen drei Öffnungen den Beckenboden: Rectum, Urethra und Vagina.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q252",topic:"t_beckenboden",cat:"anatomie",sub:"Bauch & Becken",diff:"mittel",type:"klinik",q:"Warum ist der Beckenboden nach einer vaginalen Geburt besonders gefährdet?",opts:["Durch starke Dehnung/Überlastung während der Geburt kann die Muskulatur geschwächt werden","Weil er sich während der Geburt automatisch verkürzt","Eine Geburt hat keinen Einfluss auf den Beckenboden","Weil sich dabei die Beckenknochen dauerhaft verändern"],a:0,exp:"Die starke mechanische Dehnung während der Geburt kann die Beckenbodenmuskulatur schwächen – daher ist postpartales Beckenbodentraining wichtig.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q253",topic:"t_beckenboden",cat:"anatomie",sub:"Bauch & Becken",diff:"leicht",type:"anatomie",q:"Welche Beckenbodenschicht liegt am weitesten außen?",opts:["Schließ-/Schwellkörpermuskulatur","Diaphragma pelvis","Diaphragma urogenitale","Keine der drei Schichten"],a:0,exp:"Von innen nach außen: Diaphragma pelvis, Diaphragma urogenitale, Schließ-/Schwellkörpermuskulatur.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q254",topic:"t_beckenboden",cat:"anatomie",sub:"Bauch & Becken",diff:"mittel",type:"klinik",q:"Was ist eine mögliche Folge einer chronischen Beckenbodenschwäche?",opts:["Belastungsinkontinenz","Verbesserte Sphinkterkontrolle","Erhöhte allgemeine Rumpfstabilität","Keinerlei funktionelle Folgen"],a:0,exp:"Eine Schwäche der Beckenbodenmuskulatur kann u. a. zu Belastungsinkontinenz führen, da die Sphinkterkontrolle beeinträchtigt ist.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q255",topic:"t_beckenboden",cat:"anatomie",sub:"Bauch & Becken",diff:"mittel",type:"physio",q:"Mit welchen Muskelgruppen arbeitet der Beckenboden bei der Bauchpresse funktionell eng zusammen?",opts:["Bauchwandmuskulatur und Zwerchfell","Ausschließlich die Wadenmuskulatur","Ausschließlich der M. biceps brachii","Ausschließlich die Kaumuskulatur"],a:0,exp:"Beckenboden, Bauchwandmuskulatur und Zwerchfell wirken bei der Bauchpresse hydrostatisch zusammen.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_becken_huefte (neu) ---
{id:"q256",topic:"t_becken_huefte",cat:"anatomie",sub:"Hüfte & Becken",diff:"mittel",type:"anatomie",q:"Welche Struktur führt ein Blutgefäß zur (Teil-)Ernährung des Femurkopfes?",opts:["Lig. capitis femoris","Lig. iliofemorale","Lig. inguinale","Labrum acetabuli"],a:0,exp:"Im Lig. capitis femoris verläuft ein Gefäß, das an der Ernährung des Femurkopfes beteiligt ist.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q257",topic:"t_becken_huefte",cat:"anatomie",sub:"Hüfte & Becken",diff:"leicht",type:"fakt",q:"In welchem Lebensalter verschmelzen Os ilium, Os pubis und Os ischii zum Os coxae?",opts:["14.–16. Lebensjahr","1.–2. Lebensjahr","25.–30. Lebensjahr","Bereits bei der Geburt vollständig"],a:0,exp:"Die drei Knochenanteile des Os coxae verschmelzen erst im Jugendalter (14.–16. Lebensjahr) vollständig.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
// --- t_huefte_muskulatur (neu) ---
{id:"q258",topic:"t_huefte_muskulatur",cat:"anatomie",sub:"Hüfte & Becken",diff:"mittel",type:"anatomie",q:"Welcher Nerv innerviert überwiegend die Adduktorengruppe der Hüfte?",opts:["N. obturatorius","N. femoralis","N. ischiadicus","N. gluteus superior"],a:0,exp:"Die Adduktoren (Longus, Brevis, Magnus, Gracilis, Pectineus u. a.) werden überwiegend vom N. obturatorius (L2–4) innerviert.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q259",topic:"t_huefte_muskulatur",cat:"anatomie",sub:"Hüfte & Becken",diff:"schwer",type:"verstaendnis",q:"Wie unterscheidet sich die Funktion der vorderen von den hinteren Fasern des M. gluteus medius?",opts:["Vordere Fasern flektieren/innenrotieren, hintere extendieren/außenrotieren","Beide Faseranteile wirken identisch","Nur die vorderen Fasern wirken abduzierend","Nur die hinteren Fasern stabilisieren das Becken"],a:0,exp:"Der M. gluteus medius ist Hauptabduktor; seine vorderen Fasern unterstützen zusätzlich Flexion/Innenrotation, die hinteren Extension/Außenrotation.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
// --- t_knie (neu) ---
{id:"q260",topic:"t_knie",cat:"anatomie",sub:"Knie",diff:"mittel",type:"anatomie",q:"Welches Kreuzband verhindert primär das Vorgleiten der Tibia gegenüber dem Femur?",opts:["Lig. cruciatum anterius (vorderes Kreuzband)","Lig. cruciatum posterius (hinteres Kreuzband)","Lig. collaterale mediale","Lig. collaterale laterale"],a:0,exp:"Das vordere Kreuzband (Lig. cruciatum anterius) verhindert das Vorgleiten (anteriore Translation) der Tibia gegenüber dem Femur.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q261",topic:"t_knie",cat:"anatomie",sub:"Knie",diff:"mittel",type:"verstaendnis",q:"Welche Funktion haben die Menisken bezüglich der Gelenkflächen von Femur und Tibia?",opts:["Sie gleichen die Inkongruenz der Gelenkflächen aus und verbessern die Kraftverteilung","Sie verhindern jegliche Beweglichkeit im Kniegelenk","Sie ersetzen funktionell die Kreuzbänder","Sie haben keine mechanische Stützfunktion"],a:0,exp:"Menisken gleichen die Inkongruenz zwischen Femur- und Tibiakondylen aus, verbessern die Kraftverteilung, erhöhen die Stabilität und wirken stoßabsorbierend.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
// --- t_oberschenkel_muskulatur (neu) ---
{id:"q262",topic:"t_oberschenkel_muskulatur",cat:"anatomie",sub:"Knie",diff:"leicht",type:"anatomie",q:"Welche drei Anteile des M. quadriceps femoris wirken – anders als der M. rectus femoris – rein knieextendierend ohne Hüftbeteiligung?",opts:["Vastus medialis, Vastus lateralis, Vastus intermedius","Rectus femoris, Sartorius, Gracilis","Biceps femoris, Semitendinosus, Semimembranosus","Popliteus, Gastrocnemius, Soleus"],a:0,exp:"Die drei einlenkigen Vasti (medialis, lateralis, intermedius) wirken rein knieextendierend, nur der zweigelenkige Rectus femoris flektiert zusätzlich die Hüfte.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q263",topic:"t_oberschenkel_muskulatur",cat:"anatomie",sub:"Knie",diff:"mittel",type:"verstaendnis",q:"Welche kombinierte Funktion übt die ischiocrurale Muskulatur an Hüfte und Knie aus?",opts:["Knieflexion und Hüftextension","Knieextension und Hüftflexion","Ausschließlich Knieflexion ohne Hüftbeteiligung","Ausschließlich Hüftextension ohne Kniebeteiligung"],a:0,exp:"Als zweigelenkige Muskelgruppe flektiert die ischiocrurale Muskulatur das Knie und extendiert gleichzeitig die Hüfte.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q264",topic:"t_oberschenkel_muskulatur",cat:"anatomie",sub:"Knie",diff:"leicht",type:"anatomie",q:"Wo setzt der M. quadriceps femoris gemeinsam an?",opts:["Über das Lig. patellae an der Tuberositas tibiae","Am Trochanter major","Am Tuber ischiadicum","An der Crista iliaca"],a:0,exp:"Alle vier Anteile des M. quadriceps femoris vereinigen sich zur Quadrizepssehne und setzen über das Lig. patellae an der Tuberositas tibiae an.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q265",topic:"t_oberschenkel_muskulatur",cat:"anatomie",sub:"Knie",diff:"mittel",type:"physio",q:"Welcher Muskel gilt als wichtigster aktiver Stabilisator des Kniegelenks?",opts:["M. quadriceps femoris","M. sartorius","M. gracilis","M. popliteus"],a:0,exp:"Der M. quadriceps femoris ist der wichtigste aktive Stabilisator des Kniegelenks – zentrales Ziel im Reha-Training nach Knieverletzungen.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
// --- t_usg_fuss (neu) ---
{id:"q266",topic:"t_usg_fuss",cat:"anatomie",sub:"Unterschenkel & Fuß",diff:"mittel",type:"anatomie",q:"Aus welchen zwei Gelenken setzt sich das Chopart-Gelenk zusammen?",opts:["Art. talonavicularis und Art. calcaneocuboidea","Art. talocruralis und Art. subtalaris","Art. talocalcaneonavicularis und OSG","Art. metatarsophalangeae und Art. subtalaris"],a:0,exp:"Das Chopart-Gelenk (Art. tarsi transversa) besteht aus Art. talonavicularis und Art. calcaneocuboidea.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q267",topic:"t_usg_fuss",cat:"anatomie",sub:"Unterschenkel & Fuß",diff:"mittel",type:"fakt",q:"Wie groß ist die Eversion im unteren Sprunggelenk aus der Neutral-Null-Stellung ungefähr?",opts:["ca. 10°","ca. 20°","ca. 35°","ca. 50°"],a:0,exp:"Im USG beträgt die Eversion ca. 10°, die Inversion ca. 20° (Neutral-Null-Methode).",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q268",topic:"t_usg_fuss",cat:"anatomie",sub:"Unterschenkel & Fuß",diff:"mittel",type:"anatomie",q:"Welche zwei Bandstrukturen verspannen zusammen mit der Plantaraponeurose passiv das Fußlängsgewölbe?",opts:["Pfannenband (Lig. calcaneonaviculare plantare) und Lig. plantare longum","Lig. deltoideum und Lig. talofibulare anterius","Lig. cruciatum anterius und posterius","Lig. patellae und Lig. popliteum obliquum"],a:0,exp:"Pfannenband, Lig. plantare longum und Plantaraponeurose verspannen passiv das Fußlängsgewölbe.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
// --- t_unterschenkel_muskulatur (neu) ---
{id:"q269",topic:"t_unterschenkel_muskulatur",cat:"anatomie",sub:"Unterschenkel & Fuß",diff:"mittel",type:"anatomie",q:"Welcher Nerv innerviert den M. tibialis anterior?",opts:["N. fibularis profundus","N. tibialis","N. fibularis superficialis","N. femoralis"],a:0,exp:"Der M. tibialis anterior (Dorsalextension + Inversion) wird vom N. fibularis profundus innerviert.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q270",topic:"t_unterschenkel_muskulatur",cat:"anatomie",sub:"Unterschenkel & Fuß",diff:"leicht",type:"anatomie",q:"Aus welchen zwei Muskelbäuchen besteht der M. triceps surae?",opts:["M. gastrocnemius und M. soleus","M. tibialis anterior und posterior","M. peronaeus longus und brevis","M. flexor hallucis longus und M. flexor digitorum longus"],a:0,exp:"Der M. triceps surae setzt sich aus M. gastrocnemius (zweigelenkig) und M. soleus (eingelenkig) zusammen.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q271",topic:"t_unterschenkel_muskulatur",cat:"anatomie",sub:"Unterschenkel & Fuß",diff:"schwer",type:"verstaendnis",q:"Warum wirkt nur der M. gastrocnemius – im Gegensatz zum M. soleus – zusätzlich knieflektierend?",opts:["Weil er zweigelenkig ist und oberhalb der Femurkondylen entspringt","Weil er insgesamt kräftiger ist als der M. soleus","Weil er tiefer liegt als der M. soleus","Weil er im Gegensatz zum Soleus vom N. fibularis innerviert wird"],a:0,exp:"Der M. gastrocnemius entspringt zweigelenkig oberhalb der Femurkondylen und wirkt dadurch zusätzlich kniebeugend; der eingelenkige M. soleus entspringt erst an Tibia/Fibula.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
// --- t_herz_aufbau (neu) ---
{id:"q272",topic:"t_herz_aufbau",cat:"anatomie",sub:"Herz-Kreislauf",diff:"mittel",type:"fakt",q:"Wie viel seröse Flüssigkeit befindet sich physiologisch in der Perikardhöhle?",opts:["ca. 20 ml","ca. 200 ml","ca. 2 ml","ca. 2 Liter"],a:0,exp:"Physiologisch enthält die Perikardhöhle ca. 20 ml seröse Flüssigkeit, die Reibung zwischen Epikard und Perikard verhindert.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q273",topic:"t_herz_aufbau",cat:"anatomie",sub:"Herz-Kreislauf",diff:"mittel",type:"verstaendnis",q:"Wie wachsen Herzmuskelzellen ab der Geburt, da sie sich nicht mehr teilen können?",opts:["Nur noch durch Hypertrophie (Zunahme der Zellgröße)","Durch Hyperplasie (Zellteilung)","Sie wachsen gar nicht mehr","Durch Einwanderung neuer Zellen aus dem Knochenmark"],a:0,exp:"Da sich Herzmuskelzellen postnatal nicht mehr teilen, erfolgt Wachstum nur noch durch Hypertrophie – physiologisch (Sport) oder pathologisch (Klappenfehler, Hypertonie).",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q274",topic:"t_herz_aufbau",cat:"anatomie",sub:"Herz-Kreislauf",diff:"leicht",type:"fakt",q:"Wo ist der Herzspitzenstoß typischerweise tastbar?",opts:["4./5. Interkostalraum","1. Interkostalraum","8. Interkostalraum","Direkt am Sternum"],a:0,exp:"Die frei bewegliche Herzspitze ist im 4./5. ICR nahe der Brustwand als Herzspitzenstoß tastbar.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
// --- t_herz_klappen (neu) ---
{id:"q275",topic:"t_herz_klappen",cat:"anatomie",sub:"Herz-Kreislauf",diff:"leicht",type:"fakt",q:"Wie viele Segel besitzt die Mitral-/Bikuspidalklappe?",opts:["2","3","4","1"],a:0,exp:"Die Mitralklappe (linke AV-Klappe) besitzt 2 Segel, die Trikuspidalklappe (rechts) 3 Segel.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q276",topic:"t_herz_klappen",cat:"anatomie",sub:"Herz-Kreislauf",diff:"mittel",type:"fakt",q:"Gegen welchen ungefähren Druck pumpt die linke Kammer das Blut in den Körperkreislauf?",opts:["ca. 120/80 mmHg","ca. 25/15 mmHg","ca. 200/100 mmHg","ca. 60/40 mmHg"],a:0,exp:"Die kräftigere linke Kammer (Wand ca. 11 mm) pumpt gegen den Körperkreislaufdruck von ca. 120/80 mmHg, die rechte Kammer nur gegen 25/15 mmHg im Lungenkreislauf.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
// --- t_grosse_gefaesse (neu) ---
{id:"q277",topic:"t_grosse_gefaesse",cat:"anatomie",sub:"Herz-Kreislauf",diff:"mittel",type:"anatomie",q:"Welche Herzstrukturen versorgt die rechte Herzkranzarterie (A. coronaria dextra) hauptsächlich?",opts:["Rechter Vorhof/rechte Kammer, Herzhinterwand und Großteil des Reizleitungssystems","Nur den linken Vorhof","Nur das Kammerseptum","Nur die Herzspitze"],a:0,exp:"Die A. coronaria dextra versorgt rechten Vorhof/rechte Kammer, die Herzhinterwand und die meisten Strukturen des Reizleitungssystems.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q278",topic:"t_grosse_gefaesse",cat:"anatomie",sub:"Herz-Kreislauf",diff:"leicht",type:"fakt",q:"Wie groß ist der Durchmesser der Aorta ungefähr?",opts:["2,5–3,5 cm","0,5–1 cm","5–6 cm","ca. 10 cm"],a:0,exp:"Die Aorta ist mit einem Durchmesser von 2,5–3,5 cm und einer Länge von 30–40 cm die größte Arterie des Körpers.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q279",topic:"t_grosse_gefaesse",cat:"anatomie",sub:"Herz-Kreislauf",diff:"schwer",type:"verstaendnis",q:"Warum wird die Koronarperfusion in der Systole eingeschränkt?",opts:["Weil die intramuralen Koronargefäße durch die Myokardkontraktion komprimiert werden","Weil sich die Koronararterien in der Systole aktiv weiten","Weil in der Systole kein Blut im linken Ventrikel vorhanden ist","Es besteht kein Zusammenhang zwischen Systole und Koronarperfusion"],a:0,exp:"Während der Systole komprimiert das kontrahierende Myokard die intramuralen Koronargefäße, sodass die Koronarperfusion fast ausschließlich in der Diastole erfolgt.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
// --- t_gehirn_uebersicht (neu) ---
{id:"q280",topic:"t_gehirn_uebersicht",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Welche Aufgabe wird dem Thalamus als Teil des Zwischenhirns zugeschrieben?",opts:["Sinnesfilter – selektive Weiterleitung von Reizen an den Cortex","Regulation der Herzfrequenz","Direkte Steuerung der Skelettmuskulatur","Blutbildung"],a:0,exp:"Der Thalamus fungiert als 'Tor zum Bewusstsein' und filtert/leitet Sinnesinformationen selektiv an die Großhirnrinde weiter.",src:{q:"Das Gehirn Einfuehrung und Telencephalon PDF-2.pdf",t:"quelle"}},
{id:"q281",topic:"t_gehirn_uebersicht",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"fakt",q:"Welcher Hirnabschnitt wird v. a. mit Hormonsteuerung und Schlaf-Wach-Rhythmus in Verbindung gebracht?",opts:["Zwischenhirn (Diencephalon)","Kleinhirn (Cerebellum)","Basalganglien","Rückenmark"],a:0,exp:"Das Zwischenhirn (u. a. Hypothalamus mit Hypophyse) steuert Hormonhaushalt und Schlaf-Wach-Rhythmus.",src:{q:"Das Gehirn Einfuehrung und Telencephalon PDF-2.pdf",t:"quelle"}},
// --- t_telencephalon (neu) ---
{id:"q282",topic:"t_telencephalon",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Welcher Sulcus trennt sowohl Frontal- von Parietallappen als auch Gyrus praecentralis von Gyrus postcentralis?",opts:["Sulcus centralis","Sulcus lateralis","Fissura longitudinalis cerebri","Sulcus calcarinus"],a:0,exp:"Der Sulcus centralis trennt Frontal- von Parietallappen sowie den motorischen Gyrus praecentralis vom sensorischen Gyrus postcentralis.",src:{q:"Das Gehirn Einfuehrung und Telencephalon PDF-2.pdf",t:"quelle"}},
{id:"q283",topic:"t_telencephalon",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Welche Bahnen verbinden verschiedene Kortexareale innerhalb derselben Hemisphäre?",opts:["Assoziationsbahnen","Kommissurenbahnen","Projektionsbahnen","Periphere Nervenbahnen"],a:0,exp:"Assoziationsbahnen verlaufen innerhalb einer Hemisphäre, Kommissurenbahnen (z. B. Corpus callosum) verbinden beide Hemisphären, Projektionsbahnen ziehen zu tieferen Hirnabschnitten/Rückenmark.",src:{q:"Das Gehirn Einfuehrung und Telencephalon PDF-2.pdf",t:"quelle"}},
{id:"q284",topic:"t_telencephalon",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"leicht",type:"verstaendnis",q:"Was ist typischerweise für die sprachlich-logisch dominante Großhirnhemisphäre charakteristisch?",opts:["Eher analytisch-sprachliche Verarbeitung","Eher künstlerisch-intuitive Verarbeitung ('Bauchgefühl')","Ausschließlich motorische Feinsteuerung der Beine","Ausschließlich vegetative Funktionen"],a:0,exp:"Meist ist eine Hemisphäre eher logisch-sprachlich dominant, die andere eher künstlerisch-intuitiv geprägt.",src:{q:"Das Gehirn Einfuehrung und Telencephalon PDF-2.pdf",t:"quelle"}},
// --- t_rindenfelder (neu) ---
{id:"q285",topic:"t_rindenfelder",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"leicht",type:"fakt",q:"Wie viele Rindenfelder besitzt der Cortex laut Quelle ungefähr?",opts:["ca. 200","ca. 20","ca. 2000","ca. 5"],a:0,exp:"Die Großhirnrinde umfasst bei ca. 2200 cm² Oberfläche etwa 200 unterschiedliche Rindenfelder.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
{id:"q286",topic:"t_rindenfelder",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Wo liegt das primär sensorische Rindenfeld?",opts:["Gyrus postcentralis","Gyrus praecentralis","Temporallappen (Hörzentrum)","Okzipitallappen (Sehzentrum)"],a:0,exp:"Das primär sensorische Rindenfeld (für Körperwahrnehmung) liegt im Gyrus postcentralis, hinter dem Sulcus centralis.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
{id:"q287",topic:"t_rindenfelder",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"fakt",q:"Wofür ist das Wernicke-Areal als sensorisches Sprachzentrum zuständig?",opts:["Für das Sprachverständnis","Für die motorische Sprachproduktion","Für das Sehen","Für das Riechen"],a:0,exp:"Das Wernicke-Areal ist das sensorische Sprachzentrum und für das Sprachverständnis zuständig; das Broca-Areal steuert die motorische Sprachproduktion.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
// --- t_kleinhirn_anatomie (neu) ---
{id:"q288",topic:"t_kleinhirn_anatomie",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"leicht",type:"anatomie",q:"Wo liegt das Kleinhirn (Cerebellum) anatomisch?",opts:["In der hinteren Schädelgrube, dorsal von Pons und Medulla oblongata","In der vorderen Schädelgrube","Im Temporallappen des Großhirns","Im Rückenmark"],a:0,exp:"Das Kleinhirn liegt in der hinteren Schädelgrube dorsal von Pons, Medulla oblongata und IV. Ventrikel.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q289",topic:"t_kleinhirn_anatomie",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Welche Aufgabe hat das Pontocerebellum vorwiegend?",opts:["Feinmotorik, Zielbewegungen und Sprechmuskulatur-Koordination","Gleichgewicht und Blickmotorik","Muskeltonus und Haltungskontrolle","Hormonsteuerung"],a:0,exp:"Das Pontocerebellum (größter Hemisphärenanteil, Afferenzen aus Ponskernen) ist v. a. für Feinmotorik, Zielbewegungen und Sprechkoordination zuständig.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
// --- t_hirndurchblutung (neu) ---
{id:"q290",topic:"t_hirndurchblutung",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Welche Arterie versorgt über die A. basilaris zusätzlich das Innenohr?",opts:["A. labyrinthi","A. ophthalmica","A. choroidea anterior","A. cerebri media"],a:0,exp:"Die A. labyrinthi entspringt aus dem vertebrobasilären Stromgebiet (A. basilaris) und versorgt das Innenohr.",src:{q:"Hirndurchblutung1.pdf",t:"quelle"}},
{id:"q291",topic:"t_hirndurchblutung",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Welche Arterie entspringt aus der A. carotis interna und versorgt u. a. den Plexus choroideus?",opts:["A. choroidea anterior","A. cerebri media","A. ophthalmica","A. communicans posterior"],a:0,exp:"Die A. choroidea anterior entspringt aus der A. carotis interna und versorgt u. a. den Plexus choroideus sowie Teile der Capsula interna.",src:{q:"Hirndurchblutung1.pdf",t:"quelle"}},
{id:"q292",topic:"t_hirndurchblutung",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"schwer",type:"verstaendnis",q:"Welche Funktion hat die A. communicans anterior im Circulus arteriosus cerebri?",opts:["Sie verbindet beide Aa. cerebri anteriores der jeweils rechten und linken Seite","Sie verbindet den vorderen mit dem hinteren Hirnkreislauf","Sie versorgt ausschließlich das Kleinhirn","Sie versorgt ausschließlich das Rückenmark"],a:0,exp:"Die A. communicans anterior verbindet die beiden Aa. cerebri anteriores und ermöglicht so kollaterale Versorgung im vorderen Kreislauf.",src:{q:"Hirndurchblutung1.pdf",t:"quelle"}},
// --- t_hirnstamm (neu) ---
{id:"q293",topic:"t_hirnstamm",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"fakt",q:"Welche zwei Hirnnerven zählen NICHT zu den im Hirnstamm liegenden Hirnnervenkernen?",opts:["N. olfactorius und N. opticus","N. trigeminus und N. facialis","N. vagus und N. hypoglossus","N. oculomotorius und N. trochlearis"],a:0,exp:"N. olfactorius (I) und N. opticus (II) haben ihre Kerngebiete nicht im Hirnstamm, im Gegensatz zu den übrigen Hirnnerven III–XII.",src:{q:"Hirnstamm Fragen.docx",t:"quelle"}},
{id:"q294",topic:"t_hirnstamm",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Welche zwei großen Bahnsysteme durchlaufen den Hirnstamm zwischen Rückenmark und Großhirn?",opts:["Auf- und absteigende (sensible und motorische) Bahnsysteme","Ausschließlich motorische Bahnen","Ausschließlich sensible Bahnen","Der Hirnstamm enthält keine Bahnsysteme"],a:0,exp:"Der Hirnstamm leitet sowohl aufsteigende (sensible) als auch absteigende (motorische) Bahnsysteme zwischen Rückenmark und Großhirn hindurch.",src:{q:"Hirnstamm Fragen.docx",t:"quelle"}},
{id:"q295",topic:"t_hirnstamm",cat:"anatomie",sub:"Gehirn & Nervensystem",diff:"leicht",type:"fakt",q:"Welche lebenswichtigen Funktionen werden dem Hirnstamm zugeschrieben?",opts:["Atem- und Kreislaufregulation","Ausschließlich Sehen und Hören","Ausschließlich Bewegungsplanung","Ausschließlich Gedächtnisbildung"],a:0,exp:"Der Hirnstamm reguliert u. a. lebenswichtige Funktionen wie Atmung und Kreislauf und beherbergt überlebenswichtige Reflexzentren.",src:{q:"Hirnstamm Fragen.docx",t:"quelle"}},
// --- t_herzmechanik (neu) ---
{id:"q296",topic:"t_herzmechanik",cat:"physiologie",sub:"Herz-Kreislauf",diff:"leicht",type:"anatomie",q:"Wie sind Herzmuskelzellen bezüglich ihres Zellkerns aufgebaut?",opts:["Mit einem zentralen Zellkern","Mehrkernig wie Skelettmuskelzellen","Ohne Zellkern","Mit peripher liegendem Zellkern wie Skelettmuskulatur"],a:0,exp:"Herzmuskelzellen besitzen im Gegensatz zu Skelettmuskelzellen (mehrkernig, peripher) je einen zentralen Zellkern.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q297",topic:"t_herzmechanik",cat:"physiologie",sub:"Herz-Kreislauf",diff:"mittel",type:"verstaendnis",q:"Wodurch öffnen sich die Taschenklappen während der Systole?",opts:["Durch den Druckanstieg beim Auswurf des Blutes aus der Kammer","Durch aktive Muskelkontraktion der Klappensegel","Durch Zug an Sehnenfäden","Durch den Druck im Vorhof"],a:0,exp:"Taschenklappen besitzen keine eigene Muskulatur und öffnen sich rein passiv durch den Druckanstieg beim ventrikulären Auswurf.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q298",topic:"t_herzmechanik",cat:"physiologie",sub:"Herz-Kreislauf",diff:"mittel",type:"verstaendnis",q:"Was geschieht mit der Klappen-/Ventilebene während des Herzzyklus?",opts:["Sie verschiebt sich rhythmisch mit Systole und Diastole","Sie bleibt während des gesamten Zyklus vollkommen starr","Sie existiert nur während der Systole","Sie löst sich während der Diastole vollständig auf"],a:0,exp:"Die Klappen-/Ventilebene verschiebt sich rhythmisch mit jeder Systole und Diastole – dieser Mechanismus unterstützt aktiv die Füllung der Vorhöfe.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q299",topic:"t_herzmechanik",cat:"physiologie",sub:"Herz-Kreislauf",diff:"mittel",type:"anatomie",q:"Über welche Struktur sind benachbarte Herzmuskelzellen elektrisch und mechanisch gekoppelt?",opts:["Glanzstreifen mit Gap Junctions","Sarkomere","Motorische Endplatten","Sehnenfäden (Chordae tendineae)"],a:0,exp:"An den Glanzstreifen koppeln Gap Junctions benachbarte Herzmuskelzellen elektrisch und mechanisch, sodass das Herz funktionell wie eine große Muskelzelle reagiert.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
// --- t_bewusstsein (neu) ---
{id:"q300",topic:"t_bewusstsein",cat:"physiologie",sub:"Gehirn & Nervensystem",diff:"leicht",type:"fakt",q:"Welche Bewusstseinsstufe beschreibt eine abnorme Schläfrigkeit bei noch leichter Erweckbarkeit?",opts:["Somnolenz","Sopor","Koma","Delir"],a:0,exp:"Somnolenz bezeichnet eine abnorme Schläfrigkeit, aus der der Patient noch leicht erweckbar ist – im Gegensatz zum nur durch starke Reize erweckbaren Sopor.",src:{q:"Auftrag Bewusstseinslagen Physiologie.docx",t:"quelle"}},
{id:"q301",topic:"t_bewusstsein",cat:"physiologie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Welche Hirnstrukturen aktiviert das ARAS (aufsteigendes retikuläres Aktivierungssystem) tonisch?",opts:["Großhirnrinde und Thalamus","Ausschließlich das Rückenmark","Ausschließlich das Kleinhirn","Ausschließlich die Basalganglien"],a:0,exp:"Das ARAS hält über aufsteigende Bahnen aus dem Hirnstamm die tonische Aktivierung von Thalamus und Großhirnrinde und damit den Wachzustand aufrecht.",src:{q:"Auftrag Bewusstseinslagen Physiologie.docx",t:"quelle"}},
{id:"q302",topic:"t_bewusstsein",cat:"physiologie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Worin unterscheidet sich der Wachheitszustand beim Koma von dem bei Sopor?",opts:["Beim Koma ist der Patient auch durch starke Reize nicht erweckbar, bei Sopor schon","Bei Sopor ist der Patient überhaupt nicht erweckbar","Beide Zustände sind klinisch identisch","Koma ist eine mildere Form als Sopor"],a:0,exp:"Sopor ist nur durch starke Reize durchbrechbar, beim Koma bleibt der Patient auch auf starke äußere Reize ohne Reaktion.",src:{q:"Auftrag Bewusstseinslagen Physiologie.docx",t:"quelle"}},
{id:"q303",topic:"t_bewusstsein",cat:"physiologie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"physio",q:"Welche physiotherapeutische Konsequenz kann eine reduzierte Vigilanz (z. B. Sopor) haben?",opts:["Einsatz gezielter Reizsetzung, z. B. Basaler Stimulation","Vollständige Therapiepause ohne jede Maßnahme","Ausschließlich passive Lagerung ohne jegliche Reize","Keine Anpassung der Therapie notwendig"],a:0,exp:"Bei reduzierter Vigilanz wird die Auswahl physiotherapeutischer Maßnahmen angepasst, z. B. durch gezielte Reizsetzung wie Basale Stimulation.",src:{q:"Auftrag Bewusstseinslagen Physiologie.docx",t:"quelle"}},
// --- t_pyramidenbahn (neu) ---
{id:"q304",topic:"t_pyramidenbahn",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Wo entspringt die Pyramidenbahn im Kortex?",opts:["Primär motorischer Kortex (Gyrus praecentralis, Brodmann-Areal 4)","Primär sensorischer Kortex (Gyrus postcentralis)","Okzipitallappen (Sehrinde)","Kleinhirnrinde"],a:0,exp:"Die Pyramidenbahn entspringt im primär motorischen Kortex des Gyrus praecentralis (Brodmann-Areal 4).",src:{q:"Arbeitsblatt efferente Leitungsbahnen.docx",t:"quelle"}},
{id:"q305",topic:"t_pyramidenbahn",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"An welchen Strukturen endet die Pyramidenbahn im Rückenmark?",opts:["An 2. Motoneuronen im Vorderhorn","An 1. Motoneuronen im Hinterhorn","An Interneuronen im Seitenhorn","Direkt am Muskel ohne synaptische Umschaltung"],a:0,exp:"Die Pyramidenbahn endet an den 2. Motoneuronen im Vorderhorn des Rückenmarks, die dann direkt zum Muskel ziehen.",src:{q:"Arbeitsblatt efferente Leitungsbahnen.docx",t:"quelle"}},
{id:"q306",topic:"t_pyramidenbahn",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"anatomie",q:"Woher entspringen extrapyramidale Bahnen überwiegend?",opts:["Subkortikal aus Basalganglien, Kleinhirn und Hirnstammkernen","Ausschließlich aus dem primär motorischen Kortex","Ausschließlich aus dem Rückenmark","Ausschließlich aus dem Thalamus"],a:0,exp:"Extrapyramidale Bahnen entspringen subkortikal, u. a. aus Basalganglien, Kleinhirn und Hirnstammkernen, mit variablem Kreuzungsort.",src:{q:"Arbeitsblatt efferente Leitungsbahnen.docx",t:"quelle"}},
// --- t_kleinhirninfarkt (neu) ---
{id:"q307",topic:"t_kleinhirninfarkt",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"klinik",q:"Welches Kleinhirn-Symptom wird durch raschen Wechsel von Pro- und Supination geprüft?",opts:["Dysdiadochokinese","Nystagmus","Rumpfataxie","Skandierende Sprache"],a:0,exp:"Die Dysdiadochokinese (verlangsamte, unkoordinierte schnelle Wechselbewegungen) wird u. a. durch raschen Pro-/Supinationswechsel geprüft.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q308",topic:"t_kleinhirninfarkt",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"leicht",type:"klinik",q:"Mit welchem klassischen klinischen Test wird die Dysmetrie (Vorbeigreifen am Ziel) geprüft?",opts:["Finger-Nase-Versuch","Babinski-Test","Lasègue-Test","Trendelenburg-Test"],a:0,exp:"Der Finger-Nase-Versuch ist der klassische klinische Test zur Prüfung der Dysmetrie bei Kleinhirnschädigung.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q309",topic:"t_kleinhirninfarkt",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Warum bleibt die reine Muskelkraft bei einem Kleinhirninfarkt oft weitgehend erhalten?",opts:["Weil das Kleinhirn selbst keine Bewegung auslöst, sondern nur korrigiert und koordiniert","Weil das Kleinhirn die Muskelkraft direkt steuert","Weil bei Kleinhirninfarkt immer nur eine Körperhälfte betroffen ist","Weil das Rückenmark die Kraftfunktion vollständig übernimmt"],a:0,exp:"Das Kleinhirn löst selbst keine Bewegung aus, sondern korrigiert/koordiniert sie – daher bleibt die reine Muskelkraft oft erhalten, während die Bewegungsqualität leidet.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
// --- t_rindenausfaelle (neu) ---
{id:"q310",topic:"t_rindenausfaelle",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"klinik",q:"Wie wird eine Störung bezeichnet, bei der Gesehenes trotz intakter Wahrnehmung nicht als bekannter Gegenstand erkannt wird?",opts:["(Visuelle) Agnosie","Kortikale Blindheit","Motorische Aphasie","Apraxie"],a:0,exp:"Bei einer visuellen Agnosie ist die reine Wahrnehmung intakt, aber die Bedeutungszuordnung (Erkennen) gestört – Ausfall eines sekundären Rindenfelds.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
{id:"q311",topic:"t_rindenausfaelle",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Was unterscheidet kortikale Blindheit grundsätzlich von einer Augenerkrankung?",opts:["Augen und Sehbahnen sind intakt, der Ausfall liegt in der primären Sehrinde","Bei kortikaler Blindheit sind die Augen selbst geschädigt","Bei kortikaler Blindheit ist die Sehbahn unterbrochen","Kortikale Blindheit hat keine neurologische Ursache"],a:0,exp:"Bei kortikaler Blindheit sind Augen und Sehbahnen intakt – der Funktionsverlust entsteht durch Ausfall der primären Sehrinde selbst.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
{id:"q312",topic:"t_rindenausfaelle",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"leicht",type:"fakt",q:"In welchem Hirnlappen liegt das Broca-Areal (motorisches Sprachzentrum)?",opts:["Frontallappen","Temporallappen","Parietallappen","Okzipitallappen"],a:0,exp:"Das Broca-Areal liegt frontal und steuert die motorische Sprachproduktion.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
{id:"q313",topic:"t_rindenausfaelle",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Was kennzeichnet eine motorische (Broca-)Aphasie im Unterschied zu einer reinen Sprechmuskel-Lähmung (Dysarthrie)?",opts:["Die Sprechmuskulatur ist intakt, gestört ist die zentrale Sprachsteuerung","Die Sprechmuskulatur selbst ist gelähmt","Das Sprachverständnis ist vollständig aufgehoben","Es liegt gar keine Sprachstörung vor"],a:0,exp:"Bei der Broca-Aphasie ist die Sprechmuskulatur intakt; das Problem liegt in der zentralen Steuerung des flüssigen Sprechens, das Sprachverständnis bleibt weitgehend erhalten.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
{id:"q314",topic:"t_rindenausfaelle",cat:"klinik",sub:"Gehirn & Nervensystem",diff:"leicht",type:"physio",q:"Warum ist die Unterscheidung von Broca- und Wernicke-Aphasie für die Physiotherapie praktisch relevant?",opts:["Für die interdisziplinäre Zusammenarbeit mit der Logopädie und angepasste Kommunikation in der Therapie","Weil Physiotherapeuten die Aphasie eigenständig behandeln","Weil sie keinerlei praktische Relevanz hat","Nur für die ärztliche Diagnosestellung"],a:0,exp:"Der Aphasie-Typ beeinflusst, wie in der Therapie kommuniziert wird, und ist relevant für die Zusammenarbeit mit der Logopädie.",src:{q:"Rindenfelder PDF.pdf",t:"quelle"}},
// --- t_ws_pathologie (neu) ---
{id:"q315",topic:"t_ws_pathologie",cat:"klinik",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"klinik",q:"Wie wird der Zustand bezeichnet, bei dem ausgetretenes Bandscheibenmaterial keinen Kontakt mehr zur Restbandscheibe hat?",opts:["Sequestration","Protrusion","Beginnender Prolaps","Spondylophytenbildung"],a:0,exp:"Bei der Sequestration hat das ausgetretene Bandscheibenmaterial keinen Kontakt mehr zur Restbandscheibe – das schwerste Stadium eines Bandscheibenvorfalls.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q316",topic:"t_ws_pathologie",cat:"klinik",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"verstaendnis",q:"Worauf beruht ursächlich die Zunahme von Bandscheibenschäden mit dem Alter?",opts:["Abnehmende Widerstandsfähigkeit des Anulus fibrosus und Wasserverlust des Nucleus pulposus","Zunahme des Wassergehalts der Bandscheibe im Alter","Verbesserte Durchblutung der Bandscheibe im Alter","Es besteht keine altersabhängige Veränderung"],a:0,exp:"Mit zunehmendem Alter verliert der Anulus fibrosus an Widerstandsfähigkeit und der Nucleus pulposus an Wasser – beides begünstigt Protrusionen/Prolapse.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q317",topic:"t_ws_pathologie",cat:"klinik",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"diagnostik",q:"Welche drei klinischen Informationen sind zur Höhenlokalisation eines Bandscheibenvorfalls entscheidend?",opts:["Dermatom, betroffener Kennmuskel und Reflexstatus","Nur die subjektive Schmerzstärke","Nur das Lebensalter des Patienten","Nur die Beweglichkeit der HWS"],a:0,exp:"Dermatom-Zuordnung, Kennmuskel-Prüfung und Reflexstatus (Dys-/Areflexie) erlauben die klinische Höhenlokalisation einer Nervenwurzelkompression.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q318",topic:"t_ws_pathologie",cat:"klinik",sub:"Wirbelsäule & Rumpf",diff:"leicht",type:"fakt",q:"Was versteht man unter einer Spinalkanalstenose im Rahmen degenerativer WS-Veränderungen?",opts:["Eine Einengung des Spinalkanals mit möglicher Nervenkompression","Eine Erweiterung des Spinalkanals","Eine reine muskuläre Verspannung ohne Strukturbeteiligung","Eine Überwässerung der Bandscheibe"],a:0,exp:"Eine Spinalkanalstenose ist eine degenerativ bedingte Einengung des Spinalkanals, die zu Nervenkompression und entsprechender Symptomatik führen kann.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_herzerkrankungen (neu) ---
{id:"q319",topic:"t_herzerkrankungen",cat:"klinik",sub:"Herz-Kreislauf",diff:"mittel",type:"klinik",q:"Wodurch entsteht ein Herzinfarkt pathophysiologisch meist?",opts:["Verschluss oder hochgradige Verengung einer Koronararterie durch Arteriosklerose","Entzündung des Endokards","Ansammlung von Flüssigkeit im Perikardraum","Ein angeborener Klappenfehler"],a:0,exp:"Ein Herzinfarkt entsteht meist durch arteriosklerotischen Verschluss/hochgradige Verengung einer Koronararterie mit resultierendem Sauerstoffmangel des Myokards.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q320",topic:"t_herzerkrankungen",cat:"klinik",sub:"Herz-Kreislauf",diff:"mittel",type:"verstaendnis",q:"Worin unterscheiden sich physiologische und pathologische Myokardhypertrophie hauptsächlich?",opts:["In der Ursache – z. B. Training vs. Klappenfehler/Hypertonie – nicht in der Zellstruktur selbst","Physiologische Hypertrophie betrifft nur den rechten Vorhof","Pathologische Hypertrophie kommt nur bei Kindern vor","Es gibt keinerlei Unterschied zwischen beiden Formen"],a:0,exp:"Beide Formen beruhen auf Zunahme der Zellgröße; unterschieden werden sie nach ihrer Ursache – physiologisch (z. B. Sportlerherz) oder pathologisch (Klappenfehler, Hypertonie).",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q321",topic:"t_herzerkrankungen",cat:"klinik",sub:"Herz-Kreislauf",diff:"mittel",type:"fakt",q:"Was passiert bei einer Myokardhypertrophie auf zellulärer Ebene?",opts:["Zunahme der Zellgröße, nicht der Zellzahl","Zunahme der Zellzahl durch Zellteilung","Abnahme der Zellgröße","Vollständiger Ersatz durch Bindegewebszellen"],a:0,exp:"Da sich Herzmuskelzellen postnatal nicht mehr teilen, beruht eine Hypertrophie ausschließlich auf der Zunahme der einzelnen Zellgröße.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
{id:"q322",topic:"t_herzerkrankungen",cat:"klinik",sub:"Herz-Kreislauf",diff:"schwer",type:"physio",q:"Welche physiotherapeutische Konsequenz ergibt sich aus der fehlenden Regenerationsfähigkeit des Myokards nach einem Infarkt?",opts:["Angepasstes, kontrolliertes Belastungstraining zum Erhalt der Restfunktion in der kardialen Reha","Uneingeschränktes Höchstleistungstraining ohne Anpassung","Dauerhafte vollständige Immobilisation","Keinerlei physiotherapeutische Relevanz"],a:0,exp:"Da abgestorbenes Myokard bindegewebig ersetzt und nicht regeneriert wird, ist ein individuell angepasstes Belastungstraining zentral, um die verbleibende Herzfunktion zu erhalten und zu ökonomisieren.",src:{q:"Lernfeld 4 - HKS neu.pptx",t:"quelle"}},
// --- t_pt_kleinhirn (neu) ---
{id:"q323",topic:"t_pt_kleinhirn",cat:"physiotherapie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"physio",q:"Welche Priorität hat die Sturzprophylaxe bei Patienten nach Kleinhirninfarkt?",opts:["Hohe Priorität wegen der ausgeprägten Standunsicherheit","Niedrige Priorität ohne besondere Relevanz","Gar keine Relevanz","Nur bei sehr alten Patienten relevant"],a:0,exp:"Wegen der typischen Stand-/Gangataxie und Sturzgefährdung hat die Sturzprophylaxe bei Kleinhirninfarkt-Patienten hohe Priorität.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q324",topic:"t_pt_kleinhirn",cat:"physiotherapie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"physio",q:"Welche Rolle spielt die Blickstabilisation in der Physiotherapie bei Kleinhirninfarkt?",opts:["Wichtig bei Schwindel/Nystagmus zur Unterstützung der vestibulären Kompensation","Sie spielt therapeutisch keinerlei Rolle","Nur bei isolierten Sehstörungen ohne Bezug zum Kleinhirn","Nur in der allerersten Akutphase relevant"],a:0,exp:"Bei Schwindel und Nystagmus infolge einer Vestibulocerebellum-Beteiligung sind gezielte Übungen zur Blickstabilisation und vestibulären Kompensation sinnvoll.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q325",topic:"t_pt_kleinhirn",cat:"physiotherapie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Warum steht bei Beteiligung des Spino-/Vestibulocerebellums die posturale Kontrolle im Fokus der Therapie?",opts:["Weil diese Kleinhirnanteile für Muskeltonus, Haltung und Gleichgewicht zuständig sind","Weil sie für die Sprachproduktion zuständig sind","Weil sie die Herzfrequenz regulieren","Weil sie keinerlei Bewegungsbezug haben"],a:0,exp:"Spinocerebellum (Muskeltonus/Haltung) und Vestibulocerebellum (Gleichgewicht) sind funktionell zentral für die posturale Kontrolle – daher deren Priorität in der Therapie.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q326",topic:"t_pt_kleinhirn",cat:"physiotherapie",sub:"Gehirn & Nervensystem",diff:"leicht",type:"physio",q:"Welche Alltagsprobleme können bei Kleinhirninfarkt-Patienten durch Feinmotorik-/Greifstörungen entstehen?",opts:["Schwierigkeiten bei präzisen Alltagshandlungen wie Anziehen oder Essen","Ausschließlich Sprachprobleme","Ausschließlich Sehstörungen","Keine Alltagsrelevanz"],a:0,exp:"Ungenaue Zielbewegungen (Dysmetrie) durch Pontocerebellum-Beteiligung erschweren präzise Alltagshandlungen wie Anziehen, Essen oder Schreiben.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
{id:"q327",topic:"t_pt_kleinhirn",cat:"physiotherapie",sub:"Gehirn & Nervensystem",diff:"mittel",type:"verstaendnis",q:"Warum ist bei Kleinhirninfarkt-Patienten trotz meist erhaltener Muskelkraft eine intensive Physiotherapie notwendig?",opts:["Weil die Bewegungssteuerung/-koordination gestört ist, nicht primär die Kraft","Weil die Muskulatur vollständig atrophiert ist","Weil grundsätzlich eine Lähmung vorliegt","Weil die Sensibilität vollständig fehlt"],a:0,exp:"Da das Kleinhirn die Bewegungsqualität, nicht die Kraft steuert, zielt die Therapie primär auf Koordination, Gleichgewicht und Bewegungskontrolle statt auf Krafttraining ab.",src:{q:"Kleinhirn Thieme Zusammenfassung.docx",t:"quelle"}},
// --- t_pt_wirbelsaeule (neu) ---
{id:"q328",topic:"t_pt_wirbelsaeule",cat:"physiotherapie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"verstaendnis",q:"Welche physiologische Wirkung hat die Bauchpresse mechanisch auf die Wirbelsäule?",opts:["Hydrostatische Stabilisierung, vergleichbar mit der Wand eines aufgeblasenen Balls","Vollständige Entlastung der WS ohne jede Restbelastung","Verstärkung der Bandscheibenbelastung","Keinerlei mechanische Wirkung auf die WS"],a:0,exp:"Die Bauchpresse wirkt wie die pralle Wand eines aufgeblasenen Balls und stabilisiert die Wirbelsäule hydrostatisch von innen.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q329",topic:"t_pt_wirbelsaeule",cat:"physiotherapie",sub:"Wirbelsäule & Rumpf",diff:"leicht",type:"fakt",q:"Welche vegetativen Alltagsfunktionen unterstützt die Bauchpresse neben dem Heben von Lasten?",opts:["Defäkation, Miktion und Erbrechen","Ausschließlich die Atmung in Ruhe","Ausschließlich die Verdauung im Magen","Ausschließlich die Herzfunktion"],a:0,exp:"Die Bauchpresse unterstützt neben dem Heben schwerer Lasten auch Defäkation, Miktion und Erbrechen.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q330",topic:"t_pt_wirbelsaeule",cat:"physiotherapie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"physio",q:"Warum ist ein gezieltes Aktivierungstraining der Bauchpresse bei Hebetätigkeiten physiotherapeutisch sinnvoll?",opts:["Es kann die Wirbelsäule mechanisch entlasten und Verletzungen vorbeugen","Es hat keinen messbaren Effekt auf die Belastung","Es erhöht ausschließlich die allgemeine Beweglichkeit","Es betrifft ausschließlich die Atemfunktion"],a:0,exp:"Ein gezieltes Aktivierungstraining der Bauchpresse kann bei Hebetätigkeiten die Wirbelsäule mechanisch entlasten – Grundlage rückenschonender Hebetechniken.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q331",topic:"t_pt_wirbelsaeule",cat:"physiotherapie",sub:"Wirbelsäule & Rumpf",diff:"leicht",type:"physio",q:"Für welche Alltags-/Berufssituation ist eine rückenschonende Hebetechnik mit aktivierter Bauchpresse besonders relevant?",opts:["Für Personen mit häufigem Heben schwerer Lasten im Alltag oder Beruf","Ausschließlich für Leistungssportler","Ausschließlich für bettlägerige Patienten","Sie hat keine berufliche Relevanz"],a:0,exp:"Berufe und Tätigkeiten mit häufigem Lastenheben profitieren besonders von einer trainierten, aktivierbaren Bauchpresse zur Entlastung der LWS.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
{id:"q332",topic:"t_pt_wirbelsaeule",cat:"physiotherapie",sub:"Wirbelsäule & Rumpf",diff:"mittel",type:"fakt",q:"Um wie viel Prozent kann die Bauchpresse die Bandscheibenbelastung im unteren LWS-Bereich verringern?",opts:["ca. 30%","ca. 90%","ca. 5%","Sie verringert die Belastung gar nicht"],a:0,exp:"Im unteren LWS-Bereich reduziert die Bauchpresse die Druckbelastung der Bandscheiben um ca. 30%, im oberen LWS-Bereich um bis zu 50%.",src:{q:"Anatomie Rumpf CI.pdf",t:"quelle"}},
// --- t_pt_dysbalance (neu) ---
{id:"q333",topic:"t_pt_dysbalance",cat:"physiotherapie",sub:"Hüfte & Becken",diff:"mittel",type:"physio",q:"Welche Muskelgruppe sollte bei einer Verkürzung des M. iliopsoas physiotherapeutisch primär gedehnt werden?",opts:["Der M. iliopsoas (Hüftbeuger) selbst","Die Hüftabduktoren","Die Wadenmuskulatur","Der M. quadriceps femoris"],a:0,exp:"Bei verkürztem, überaktivem M. iliopsoas steht dessen gezielte Dehnung im Vordergrund, um Beckenkippung und Hyperlordose entgegenzuwirken.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q334",topic:"t_pt_dysbalance",cat:"physiotherapie",sub:"Hüfte & Becken",diff:"leicht",type:"verstaendnis",q:"Welche Ursachen begünstigen muskuläre Dysbalancen im Alltag typischerweise?",opts:["Fehlhaltungen, Bewegungsmangel und einseitige berufliche Belastung","Ausschließlich genetische Faktoren","Ausschließlich akute Verletzungen","Ausschließlich das Lebensalter"],a:0,exp:"Fehlhaltungen (z. B. am Arbeitsplatz), mangelnde Bewegung und einseitige berufliche Bewegungsmuster begünstigen muskuläre Dysbalancen.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q335",topic:"t_pt_dysbalance",cat:"physiotherapie",sub:"Hüfte & Becken",diff:"mittel",type:"physio",q:"Welche Muskeln sollten bei einer typischen Hüftbeuger-Dysbalance zusätzlich gezielt gekräftigt werden?",opts:["Hüftabduktoren/Glutealmuskulatur","Ausschließlich die Bauchmuskulatur","Ausschließlich die Wadenmuskulatur","Ausschließlich die Nackenmuskulatur"],a:0,exp:"Neben der Dehnung des verkürzten Hüftbeugers ist die Kräftigung der Hüftabduktoren/Glutealmuskulatur zentral, um das muskuläre Gleichgewicht wiederherzustellen.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q336",topic:"t_pt_dysbalance",cat:"physiotherapie",sub:"Hüfte & Becken",diff:"mittel",type:"verstaendnis",q:"Was passiert funktionell mit einem Muskel, der über längere Zeit kaum Bewegungsreize erhält?",opts:["Er atrophiert (baut ab)","Er hypertrophiert automatisch","Er verkürzt sich automatisch wie sein Gegenspieler","Es findet keine Veränderung statt"],a:0,exp:"Muskeln, die kaum Reize erhalten, bauen ab (Atrophie) – dies betrifft häufig den Antagonisten eines überaktiven, verkürzten Muskels.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
{id:"q337",topic:"t_pt_dysbalance",cat:"physiotherapie",sub:"Hüfte & Becken",diff:"schwer",type:"verstaendnis",q:"Welche zwei Faktoren können neben reiner Kraft- und Dehnfähigkeit die Gelenkfunktion zusätzlich beeinträchtigen?",opts:["Störungen des muskulären Gleichgewichts und der Bewegungskoordination","Ausschließlich die Gelenkschmiere (Synovia)","Ausschließlich das Knochenwachstum","Ausschließlich die Hautspannung über dem Gelenk"],a:0,exp:"Neben Kraft und Dehnfähigkeit einzelner Muskeln beeinträchtigen auch Störungen des muskulären Gleichgewichts und der Bewegungskoordination die Gelenkfunktion.",src:{q:"Anatomie Untere Extremitaet CI gesamt - Revision-2.pdf",t:"quelle"}},
